//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JS_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joc
    {
        public int id { get; set; }
        public Nullable<int> whitePlayer { get; set; }
        public Nullable<int> blackPlayer { get; set; }
        public string moveList { get; set; }
    }
}
