//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JS_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilizatori
    {
        public int id { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string Username { get; set; }
        public string Parola { get; set; }
        public string tara { get; set; }
        public Nullable<int> raiting { get; set; }
        public string titlu { get; set; }
    }
}
